config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', action: :about, controller: 'pages'
  resources :tweets, only: [:create, :show]
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets


  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :followeds, through: :active_relationships, source: :followed
  
  has_many :passive_relationships, class_name: 'Relationship',
                                  foreign_key: 'followed_id',
                                  dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  

  def follows?(other_user)
    followeds.include?(other_user)
  end

  def follow!(other_user)
    active_relationships.create(followed: other_user)
    # Also works:
    # followed.push other_user
  end

  def unfollow!(followed_user)
    followeds.delete(followed_user)
  end

  def feed
    users_ids = followers.pluck(:id)
    users_ids.push self.id
    Tweet.where(user_id: users_ids).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
      if user_signed_in?
        @tweet = current_user.tweets.build
      end
	end

  def about
    
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:id])

    if current_user.follows? @user      
      redirect_to user_path(@user), alert: 'Usuário já está sendo seguido!'
    else
      current_user.follow! @user
      redirect_to user_path(@user), notice: 'Usuário seguido com sucesso!'
    end
  end

  def destroy
    pry
    @user = User.find(params[:id])
    current_user.unfollow! @user
    redirect_to user_path(@user), notice: 'Usuário deixou de ser seguido com sucesso!'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def create
        @tweet = current_user.tweets.new(tweet_params)
        
        if @tweet.save
          redirect_to :root, notice: 'Tweet criado!'
        else
          redirect_to :root, notice: 'Tweet não criado!'
        end
    end

    def show
      @tweet = Tweet.find(params[:id])
    end
    
    private
      def tweet_params
        params.require(:tweet).permit(:content)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter Clone: Aline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li> <%= link_to "Home", root_path %> </li>
        <li> <%= link_to "Users", users_path %> </li>
        <li> <%= link_to "About", about_path %> </li>

        <% if user_signed_in? %>
          <li> <%= link_to "Profile", user_path(current_user) %> </li>
          <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </header>
  	<div class="notificacoes">
  		<p class="notice"> <%= notice %> </p>
  		<p class="alert"> <%= alert %></p>
  	</div>
  	
  	<section>
    	<%= yield %>
    </section>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>

<% unless user_signed_in? %>

  <%= link_to 'Sign In here', new_user_session_path %> | <%= link_to 'Sign up here', '#' %>

<% else %>

  <p>Olá, <%= current_user.email %></p>

  <%= form_for(@tweet) do |f| %>
    <%= f.text_field :content %>
    <%= f.submit %>
  <% end %>
  
  <h1>Feed</h1>
  <ul>
    <% current_user.feed.each do |tweet| %>
      <li> <%= tweet.content %> </li>
    <% end %>
  </ul>
<% end %>

app/views/relationships/_follow_unfollow_button.html.erb
<% if current_user.follows? other_user %>
  <%= link_to 'Unfollow', # %>
<% else %>
  <%= link_to 'Follow', # %>
<% end %>

app/views/users/index.html.erb
<h1>Usuários</h1>
<ul>
  <% @users.each do |user| %>
    <li> <%= link_to user.email, user_path(user) %> </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.email %> </h1>

<% unless @user == current_user %>
  <% if current_user.follows? @user %>
    <%= link_to 'Unfollow', relationship_path(@user), method: :delete %>
  <% else %>
    <%= link_to 'Follow', relationships_path(id: @user.id), method: :post %>
  <% end %>
<% end %>

<h2> Tweets (<%= @user.tweets.count %>) </h2>
<% if @user.tweets.empty? %>
  <p>Usuário ainda não tem tweets</p>
<% else %>
  <ul>
    <% @user.tweets.each do |tweet| %>
      <li> <%= tweet.content %> </li>
    <% end %>
  </ul>
<% end %>